### ISSUE TITLE
Add abbreviation does not work

### ISSUE THREAD

**Issue by rayvermey** [autokey/autokey#1013]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Xorg

### Has this issue already been reported?

- [x] I have searched through the existing issues.

### Is this a question rather than an issue?

- [x] This is not a question.

### What type of issue is this?

Bug

### Choose one or more terms that describe this issue:

- [ ] autokey triggers
- [x] autokey-gtk
- [ ] autokey-qt
- [ ] beta
- [x] bug
- [ ] critical
- [ ] development
- [ ] documentation
- [ ] enhancement
- [ ] installation/configuration
- [ ] phrase expansion
- [ ] scripting
- [ ] technical debt
- [ ] user interface

### Which Linux distribution did you use?

Arch Linux

### Which AutoKey GUI did you use?

None

### Which AutoKey version did you use?

autokey-gtk Version 0.96.0

### How did you install AutoKey?

AUR

### Can you briefly describe the issue?

Hi, when I open the main screen on my Linux system and want to add an abbreviation for a text 
I can add the abbreviation in the left screen but the OK button on the right does nothing....
So I click SET, then ADD and enter, and then when I click OK nothing happens.
I deleted and installed the app again but still the same.
I use Arch, btw :-)
What must I do?
Thanks
Ray

### Can the issue be reproduced?

Always

### What are the steps to reproduce the issue?

1. RMC on Autokey icon
2. Show main window
3. click on the phrase
4. click SET by Abbreviations
5. click ADD
6. type the abbrev like ATH
7. return key so the abbrev is shown
8. Press OK.. THAT does do nothing

### What should have happened?

(None configured should be replaced by ATH abbreviaton

### What actually happened?

nothing.. Window stays on screen

### Can you provide the output of the AutoKey command?

```bash

```

<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💵 Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount).<br/>🕵️‍♂️ If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #1013</code> either in the PR description or in a PR's comment.<br/><br/>🪙 Also, everyone can tip any user commenting <code>/tip 20 @rayvermey</code> (replace <code>20</code> with the amount, and <code>@rayvermey</code> with the user to tip).<br/><br/>📖 If you want to learn more, check out our <a href="https://docs.opire.dev">documentation</a>.</details>

**Comment by Elliria** [comment]
It looks like you're missing the final step:

9. Save the phrase by picking one:
   * Click the **Save** button in the toolbar.
   * Open the **File** menu and click **Save** in its drop-down.
   * Press the **Ctrl**+**s** key-combination.
   * Click on another phrase or script (AutoKey automatically saves the previous one).

**Comment by rayvermey** [comment]
Sorry but the window with the abbreviations just stays, keeps active if I click OK so File -> Save etc does not work.....

Ray

**Comment by josephj11** [comment]
@rayvermey You shouldn't need to do this any more, but try the following:

Do it exactly the way you were doing it, but right after typing the new abbreviation, press the Enter key, then continue as before. That used to be necessary (and undocumented) in all releases before 0.96.0.

**Comment by rayvermey** [comment]
Hitting the Enter key shows OK being clicked so to speak but the windoiw stays on top, does not dissappear and the abbrev is not set.
In some way the Window where I set the (new) abbreviation does not go away when I press Enter or click OK.
What can this be?

**Comment by josephj11** [comment]
This one's got me stumped. Have to get a dev to work on it.

In the mean time, once your new action is saved, you can set things manually.

In a terminal or file manager, go to where the action is saved. By default, this is in a  folder under `$HOME/.config/autokey/data`.  If it's an action, named xxx, there will be a file named xxx.json.

Make a backup of the file such as xxx.json.save so you can retore it if things don't work.

Edit this file directly with a text editor such as kate or nano.

Find a section that looks like this:

```
 "abbreviation": {
        "wordChars": "[\\w]", 
        "abbreviations": [
            "AKG!"
        ], 
        "immediate": true, 
        "ignoreCase": false, 
        "backspace": true, 
        "triggerInside": false
    }, 
  ```
Here you can manually enter the abbreviation (where I have `AKG!` above). Be careful not to change anything accidentally.
When you are done, you will probably have to terminate and restart AutoKey for your changes to take effect.

This is serously inellegant, but it should work.

We have a few interested developers, but no one doing regular development, so finding and fixing problems like this might take a long time.

**Comment by rayvermey** [comment]
Hi, this is my json file but after restarting autokey-gtk it still does not work.....

{
    "type": "phrase",
    "description": "athletic_shoe",
    "modes": [],
    "usageCount": 1,
    "prompt": false,
    "omitTrigger": false,
    "matchCase": false,
    "showInTrayMenu": true,

"abbreviation": {
        "wordChars": "[\\w]",
        "abbreviations": [
            ":ath:"
        ],
        "immediate": true,
        "ignoreCase": false,
        "backspace": true,
        "triggerInside": false
    },

    "hotkey": {
        "modifiers": [],
        "hotKey": null
    },
    "filter": {
        "regex": null,
        "isRecursive": false
    },
    "sendMode": "<ctrl>+v"
}

**Comment by rayvermey** [comment]
Btw , this seems an Archlinux thing...
I started another Arch vm, same problem.
I specially installed a Linuxmint machine, installed autokey-gtk there and all functions normal...

Thought let you know.

Ray

**Comment by josephj11** [comment]
@rayvermey Arch is not for the faint of heart! :) But we do have a number of Arch and Manjaro users.
You may want to post about this on our [Forum](https://groups.google.com/forum/#!forum/autokey-users) or on [Gitter](https://gitter.im/autokey/autokey) where more of our users will see it. Be sure to mention Arch.

Several things to try:

First and foremost, make sure you're using x11 and not Wayland. We are actively working on Wayland, but it does not work in 0.96.0 or earlier.

Run `echo $XDG_SESSION_TYPE` in a terminal window. It should emit `x11`.

Run a [trace](https://github.com/autokey/autokey/wiki/Troubleshooting) using your phrase.

Try another abbreviation that does not include non-word characters, like xxxx and see if that makes a difference.

Just to make sure your phrase works at all, edit it in the GUI and select Show in notification icon menu.
Then open a text editor window with an empty file and click on the AutoKey panel icon and click on the entry for your phrase
This should expand your phrase in the text editor window. If it doesn't, then we have bigger problems and a trace might help.

**Comment by Elliria** [comment]
Can you do the trace exactly the way I did it so we can compare our traces to see what's different?

1. Open a terminal window.
2. Run AutoKey in debug mode:
   ```bash
   autokey-gtk -lc
   ```
3. Click on a phrase or script that doesn't have an abbreviation.
4. Click the **Set** button on the **Abbreviations** line at the bottom.
5. Click the **+Add** button.
6. Type in the abbreviation (example: `abc`).
7. Press the **Enter** key.
8. Click the **OK** button.
9. Click the **Save** button in the toolbar.
10. Exit AutoKey.
11. Copy everything in the terminal window into a text file.
12. Drag the text file into a message here.

Here's my output: [debugoutput.log](https://github.com/user-attachments/files/18660815/debugoutput.log)

Also, here's a really wild guess as to what might be happening that you might want to look into. I'm curious what happens if you run this command in a terminal window on the Linux Mint machine and in the Arch VM and then press and release the **Enter** key:
```
xev | grep keycode
```
I get keycode **36** when I do that in Kubuntu 22.04 LTS. Maybe that's the keycode AutoKey is expecting and maybe Arch puts out something different.

If Arch gives you a different keycode, you could try pressing all of the keys on your keyboard one by one until you find one that gives you keycode **36** (note that you can press as many keys as you like as long as that terminal window is open and it will spit out the keycode for each one until you close the window). Then, press that key **instead of** the **Enter** key in step 7 above to see if that fixes it.

Last, but not least, and still wildly guessing, does the **Enter** key have any significance to your VMs? Like, for instance, my right **Ctrl** key has significance to my VMs and is intercepted by them.

**Comment by rayvermey** [comment]
Hi, here is my log and it shows an Python error!
Can you see what is going on?
Cheers

Ray

[ak-log.txt](https://github.com/user-attachments/files/18661486/ak-log.txt)

**Comment by josephj11** [comment]
The error was caused by upgrading to Python 3.13 which we and GitHub don't support yet. It's fixed in our development branch, but there is no target date for a new release. You can either figure out how to run with 3.12 or fix the syntax of a few next's in the code base. @Elliria probably knows where the PR to fix that is so you can see how to fix it. I didn't see it immediately.

**Comment by Elliria** [comment]
Yep. @josephj11 got it. This is related to issue #974 and can be solved by replacing the `next()` method with the new built-in `next()` function in the **dialogs.py** file. This will be done in future releases of AutoKey, but isn't in the currently-released versions.

To see if it will solve the issue for you, you can edit and run a clone of AutoKey:
1. Follow step 1 and 2 of [these instructions for trying out a clone of AutoKey](https://github.com/autokey/autokey/wiki/Running-Tests#trying-out-a-clone-of-autokey).
2. Open the `lib/autokey/gtkui/dialogs.py` file in a text editor.
3. Find this line:
   ```python
   text = model.get_value(i.next().iter, 0)
   ```
4. Replace it with this line:
   ```python
   text = model.get_value(next(i).iter, 0)`
   ```
5. Save the file.
6. Follow steps 3 through 5 of [these instructions for trying out a clone of AutoKey](https://github.com/autokey/autokey/wiki/Running-Tests#trying-out-a-clone-of-autokey).

**Comment by Mizokuiam** [comment]
Hi @rayvermey,

Here's a suggested solution for this issue:

The issue described suggests a problem with the AutoKey GUI responsiveness, likely due to a conflict or misconfiguration within the Arch Linux environment.  Since reinstallation didn't solve the problem, let's try some troubleshooting steps.  The core issue is the OK button not responding after adding an abbreviation.  Unfortunately, without more specific error messages or logs, it's hard to pinpoint the exact cause. The provided steps don't include running AutoKey from the command line which could offer valuable debugging information.

**Possible Solutions and Troubleshooting Steps:**

1. **Run AutoKey from the terminal:**

   This will allow you to see any error messages that might be hidden when running it from the system tray.  Open a terminal and run:

   ```bash
   autokey-gtk
   ```

   Observe any output in the terminal when trying to add an abbreviation. This may provide clues.

2. **Check for conflicting applications:**

   Other keyboard shortcut or automation tools might be interfering with AutoKey.  Temporarily disable any other similar applications to see if the problem persists.

3. **Reset AutoKey Configuration:**

   Sometimes corrupted configuration files can cause unexpected behavior. Try resetting AutoKey's configuration.  First, **backup your current configuration!**  Then, locate the AutoKey configuration directory (usually `~/.config/autokey`) and rename or move it. AutoKey will create a new, default configuration on next startup.

   ```bash
   mv ~/.config/autokey ~/.config/autokey_backup
   ```

4. **Reinstall with dependencies:**

   Sometimes AUR packages can have dependency issues. Try reinstalling AutoKey, ensuring all dependencies are met. You can use `yay` or `pamac` (if installed) which handle dependencies better than `makepkg`. For Example (with `yay`):

   ```bash
   yay -S autokey-gtk
   ```

5. **Check Python and GTK versions:**

   Ensure you have compatible versions of Python and GTK installed.  AutoKey-gtk relies on these.  Check the AutoKey documentation for specific version requirements. You can check your versions with:

   ```bash
   python --version
   pacman -Q gtk3 # Or gtk4 depending on AutoKey's requirements
   ```

6. **Permissions:**

   Though less likely, ensure your user has proper read/write permissions to the AutoKey configuration directory (`~/.config/autokey`).

7. **Look for system logs:**

   Check your system logs (e.g., `/var/log/syslog` or `/var/log/Xorg.0.log`) for any error messages related to AutoKey.



**Example of adding an abbreviation (within AutoKey script):**

While the issue is with the GUI, understanding the underlying scripting can be helpful. Here’s how you'd add an abbreviation programmatically:

```python
# Define the abbreviation and the phrase it expands to.
abbreviation = "ATH"
phrase = "This is the expanded text for ATH."

# Add the abbreviation.
system.add_abbreviation(abbreviation, phrase)

# Optional: Save the changes.
store.save()

# Notify the user that the abbreviation has been added.
keyboard.send_keys("<ctrl>+alt+a") # Example notification using a hotkey.  Adapt as needed.
```


By following these steps, you should be able to gather more information about the issue and hopefully find a solution. Remember to provide more detailed error messages or logs if you continue to experience problems, as this will greatly assist in further debugging.

**Comment by josephj11** [comment]
@Mizokuiam Your suggestion here looks mostly like a hallucination. Please don't contribute code that you are not able to run and test first.

**Comment by Elliria** [comment]
Yep. That's a bot.

> [!CAUTION]
> I wouldn't recommend trying out its code.

**Comment by dlk3** [comment]
I agree with @Elliria

**Comment by Mizokuiam** [comment]
> [@Mizokuiam](https://github.com/Mizokuiam) Your suggestion here looks mostly like a hallucination. Please don't contribute code that you are not able to run and test first.

i might went confused on my suggested solution, but not hallucinating as you thought so!

**Comment by pheek** [comment]
Same problem on lubuntu using lxqt.

I have autokey configured on another linux (lxde) and then copyed ~/.config/autokey to this lxqt (both PCs uses lubuntu).
Here on lxqt I am not able to configure abbrevations (same issue).

python --version does not work, because I am using python3
python3 --version bring 3.13.3

**Comment by Elliria** [comment]
I'm sorry about that, @pheek. Is the solution given in issue [#646](https://github.com/autokey/autokey/issues/646) or issue [#1048](https://github.com/autokey/autokey/issues/1048) of any use to you in solving this?

**Comment by Elliria** [comment]
Related issues:
* [issue #646](https://github.com/autokey/autokey/issues/646)
* [issue #1048](https://github.com/autokey/autokey/issues/1048)
* [issue #1059](https://github.com/autokey/autokey/issues/1059)
* [issue #974](https://github.com/autokey/autokey/issues/974)

**Comment by Elliria** [comment]
Closing this issue manually since the issue has been resolved in pull request #1076.
