### ISSUE TITLE
Failure to grab keyboard in Fedora 30

### ISSUE THREAD

**Issue by dlewis7444** [autokey/autokey#293]
## Classification:

Bug

## Reproducibility:

Always

## Version

AutoKey version:
autokey-gtk-0.95.7-2.fc30.noarch

Used GUI (Gtk, Qt, or both):
GTK

If the problem is known to be present in more than one version, please list all of those.

Installed via: (PPA, pip3, …).
dnf

Linux Distribution:
Fedora 30

## Summary

Summary of the problem.
When setting hotkey using "Press key to set", keyboard is not grabbed.

## Steps to Reproduce (if applicable)

- Create phrase or select existing one
- Click "Set" for Hotkey
- Click "Press to Set"
- Try any hotkey and it will not grab it.  See logs
- It appears to not be grabbing existing hotkeys either - such as super-k to bring up window

## Expected Results

- Should set the hotkey

## Actual Results

- Doesn't.

If helpful, submit screenshots of the issue to help debug.\
Debugging output, obtained by launching autokey via `autokey-gtk --verbose` (or `autokey-qt --verbose`, if you use the Qt interface) is also useful.\
Please upload the log somewhere accessible or put the output into a code block (enclose in triple backticks).
```
2019-06-24 16:41:02,324 ERROR - interface - Error in X event loop thread
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/autokey/interface.py", line 242, in __eventLoop
    method(*args)
  File "/usr/lib/python3.7/site-packages/autokey/interface.py", line 674, in __grab_keyboard
    focus.grab_keyboard(True, X.GrabModeAsync, X.GrabModeAsync, X.CurrentTime)
AttributeError: 'int' object has no attribute 'grab_keyboard'
```

**Comment by dlewis7444** [comment]
The log entries above occur immediately upon clicking "Press to Set"

Also, the icon does not show in the system tray.

**Comment by josephj11** [comment]
Until Thomas has time to address this:

We are not seeing an issue like this elsewhere, so maybe there is something "wrong" on your system. It sounds like an installation problem. This would occur if some dependencies are not quite right or the dnf package has issues.

Until Thomas (our current developer) can comment, you might want to try uninstalling AutoKey and [reinstalling](https://github.com/autokey/autokey/wiki/Installing) using pip3. (Be sure to backup your existing phrases and scripts first - including the hidden files.)

Even if this doesn't fix the issue, it may produce some additional messages pointing to the actual issue.

Just to make sure I understand the issue, this occurs when you are attempting to assign the hotkey for a script or phrase. If this is the case, what else is broken?

Can you run a script from the main AutoKey menu using Tools->Run Script?
Can you run the example scripts using the hotkeys which are already assigned to them?

**Comment by dlewis7444** [comment]
dnf remove autokey-gtk, then installed with pip3.  (Version available was older: 0.95.4).

Same issue.

Correct, this occurs when I attempt to assign a hotkey.  When pressing any key while autokey or gnome-terminal is in the foreground, the log (autokey-gtk -l) does not show the key capture.  Hotkeys do not work.

But, in Firefox, the log does show every keystroke and existing hotkeys work (ctrl-f7 for the "My Phrases" folder).

Also, the icon is missing.  (Yes, "Show a notification icon" is checked.)

Tools -> Run Script works.

**Comment by luziferius** [comment]
Thank you for reporting this. The given traceback is useful and gives a good hint why it does not work.

Hmmm. X11 windows are organized in a [tree-like structure](https://en.wikipedia.org/wiki/Tree_(data_structure)). If AK wants to grab a global hotkey, it has to do it at the root window (which is the screen). At some point travelling upwards, the used library returns a simple number instead of an actual window object. I don’t know why it does so, but it does it since at least 6 years.

Here is a workaround in a somewhat unrelated function, where it deals with exactly this:
https://github.com/autokey/autokey/blob/35decb72f286ce68cd2a1f09ace8891a520b58d1/lib/autokey/interface.py#L1092-L1101

I assume that the code walks the tree one level too high for some reason. It then passes the returned `int`-number around until it breaks.

If you only have one or two hotkeys and you want to get it done _now_, you can edit the hidden script/phrase metadata `.json` file yourself. Alongside each script is a hidden file that contains it's configuration. The file looks like this https://github.com/luziferius/autokey_scripts/blob/master/NumpadIME/.NumpadIME_key_9.json . Open it in a text editor and fill in the hotkey you want. The modifiers, if any, go into the `modifiers` list individually. Use this as a reference for special keys: https://github.com/autokey/autokey/blob/master/lib/autokey/iomediator/key.py

It is not ideal, but gets the job done now rather than later.

**Comment by shrestaz** [comment]
I'm having the same issue on a fresh install of Fedora 30 with `autokey-gtk`. As a workaround, `autokey-qt` works fine and captures the keyboard events.

**Comment by luziferius** [comment]
@shrestaz Thanks. Then it is an issue with the GTK GUI or how the GTK GUI uses the shared core functionality. It narrows the possible error sources down.

**Comment by dlewis7444** [comment]
Cool workaround.  I just now tested it (without any workaround), however, and it's grabbing the keys.  Yay!

My "A" icon is still missing though.  Minor annoyance.  Should I open a ticket for that?  I'm good with living with it.

I ran 3 full updates since I last tested autokey - that's probably why it started working.  List of packages that were updated:

    Upgrade  gdb-8.3-4.fc30.x86_64                            @updates-testing
    Upgrade  gdb-headless-8.3-4.fc30.x86_64                   @updates-testing
    Upgrade  gstreamer1-plugins-bad-free-1.16.0-2.fc30.x86_64 @updates-testing
    Upgrade  gupnp-1.0.4-1.fc30.x86_64                        @updates-testing
    Upgrade  kernel-headers-5.1.15-300.fc30.x86_64            @updates-testing
    Upgrade  libinput-1.13.3-1.fc30.x86_64                    @updates-testing
    Upgrade  libnfsidmap-1:2.4.1-0.fc30.x86_64                @updates-testing
    Upgrade  libxcrypt-4.4.6-2.fc30.i686                      @updates-testing
    Upgrade  libxcrypt-4.4.6-2.fc30.x86_64                    @updates-testing
    Upgrade  libxcrypt-devel-4.4.6-2.fc30.x86_64              @updates-testing
    Upgrade  mesa-dri-drivers-19.0.7-1.fc30.i686              @updates-testing
    Upgrade  mesa-dri-drivers-19.0.7-1.fc30.x86_64            @updates-testing
    Upgrade  mesa-filesystem-19.0.7-1.fc30.i686               @updates-testing
    Upgrade  mesa-filesystem-19.0.7-1.fc30.x86_64             @updates-testing
    Upgrade  mesa-libEGL-19.0.7-1.fc30.x86_64                 @updates-testing
    Upgrade  mesa-libGL-19.0.7-1.fc30.i686                    @updates-testing
    Upgrade  mesa-libGL-19.0.7-1.fc30.x86_64                  @updates-testing
    Upgrade  mesa-libOpenCL-19.0.7-1.fc30.x86_64              @updates-testing
    Upgrade  mesa-libgbm-19.0.7-1.fc30.x86_64                 @updates-testing
    Upgrade  mesa-libglapi-19.0.7-1.fc30.i686                 @updates-testing
    Upgrade  mesa-libglapi-19.0.7-1.fc30.x86_64               @updates-testing
    Upgrade  mesa-libxatracker-19.0.7-1.fc30.x86_64           @updates-testing
    Upgrade  mesa-vulkan-drivers-19.0.7-1.fc30.i686           @updates-testing
    Upgrade  mesa-vulkan-drivers-19.0.7-1.fc30.x86_64         @updates-testing
    Upgrade  mutter-3.32.2-2.fc30.x86_64                      @updates-testing
    Upgrade  nfs-utils-1:2.4.1-0.fc30.x86_64                  @updates-testing
    Upgrade  python-qt5-rpm-macros-5.12.2-5.fc30.noarch       @updates-testing
    Upgrade  python3-gobject-3.32.2-1.fc30.x86_64             @updates-testing
    Upgrade  python3-gobject-base-3.32.2-1.fc30.x86_64        @updates-testing
    Upgrade  python3-pyqt5-sip-4.19.17-1.fc30.x86_64          @updates-testing
    Upgrade  python3-qt5-5.12.2-5.fc30.x86_64                 @updates-testing
    Upgrade  python3-qt5-base-5.12.2-5.fc30.x86_64            @updates-testing
    Upgrade  python3-qt5-webkit-5.12.2-5.fc30.x86_64          @updates-testing
    Upgrade  python3-speechd-0.9.1-1.fc30.x86_64              @updates-testing
    Upgrade  qgnomeplatform-0.5-10.fc30.x86_64                @updates-testing
    Upgrade  qt5-qtbase-5.12.4-1.fc30.x86_64                  @updates-testing
    Upgrade  qt5-qtbase-common-5.12.4-1.fc30.noarch           @updates-testing
    Upgrade  qt5-qtbase-gui-5.12.4-1.fc30.x86_64              @updates-testing
    Upgrade  qt5-qtconnectivity-5.12.4-1.fc30.x86_64          @updates-testing
    Upgrade  qt5-qtdeclarative-5.12.4-1.fc30.x86_64           @updates-testing
    Upgrade  qt5-qtenginio-1:1.6.2-24.fc30.x86_64             @updates-testing
    Upgrade  qt5-qtlocation-5.12.4-1.fc30.x86_64              @updates-testing
    Upgrade  qt5-qtmultimedia-5.12.4-1.fc30.x86_64            @updates-testing
    Upgrade  qt5-qtsensors-5.12.4-1.fc30.x86_64               @updates-testing
    Upgrade  qt5-qtserialport-5.12.4-1.fc30.x86_64            @updates-testing
    Upgrade  qt5-qtsvg-5.12.4-1.fc30.x86_64                   @updates-testing
    Upgrade  qt5-qttools-common-5.12.4-1.fc30.noarch          @updates-testing
    Upgrade  qt5-qttools-libs-designer-5.12.4-1.fc30.x86_64   @updates-testing
    Upgrade  qt5-qttools-libs-help-5.12.4-1.fc30.x86_64       @updates-testing
    Upgrade  qt5-qtwayland-5.12.4-1.fc30.x86_64               @updates-testing
    Upgrade  qt5-qtwebchannel-5.12.4-1.fc30.x86_64            @updates-testing
    Upgrade  qt5-qtwebkit-5.212.0-0.36.alpha2.fc30.x86_64     @updates-testing
    Upgrade  qt5-qtwebsockets-5.12.4-1.fc30.x86_64            @updates-testing
    Upgrade  qt5-qtx11extras-5.12.4-1.fc30.x86_64             @updates-testing
    Upgrade  qt5-qtxmlpatterns-5.12.4-1.fc30.x86_64           @updates-testing
    Upgrade  qt5-srpm-macros-5.12.4-1.fc30.noarch             @updates-testing
    Upgrade  speech-dispatcher-0.9.1-1.fc30.x86_64            @updates-testing
    Upgrade  speech-dispatcher-espeak-ng-0.9.1-1.fc30.x86_64  @updates-testing
    Upgrade  squashfs-tools-4.3-21.fc30.x86_64                @updates-testing
    Upgrade  xorg-x11-server-Xorg-1.20.5-2.fc30.x86_64        @updates-testing
    Upgrade  xorg-x11-server-Xwayland-1.20.5-2.fc30.x86_64    @updates-testing
    Upgrade  xorg-x11-server-common-1.20.5-2.fc30.x86_64      @updates-testing
    Upgrade  thunderbird-60.7.2-2.fc30.x86_64                 @updates

    Upgrade  cockpit-197-1.fc30.x86_64                                   @updates-testing
    Upgrade  cockpit-bridge-197-1.fc30.x86_64                            @updates-testing
    Upgrade  cockpit-dashboard-197-1.fc30.noarch                         @updates-testing
    Upgrade  cockpit-networkmanager-197-1.fc30.noarch                    @updates-testing
    Upgrade  cockpit-packagekit-197-1.fc30.noarch                        @updates-testing
    Upgrade  cockpit-storaged-197-1.fc30.noarch                          @updates-testing
    Upgrade  cockpit-system-197-1.fc30.noarch                            @updates-testing
    Upgrade  cockpit-ws-197-1.fc30.x86_64                                @updates-testing
    Upgrade  createrepo_c-0.14.2-1.fc30.x86_64                           @updates-testing
    Upgrade  createrepo_c-libs-0.14.2-1.fc30.x86_64                      @updates-testing
    Upgrade  dnf-4.2.5-2.fc30.noarch                                     @updates-testing
    Upgrade  dnf-data-4.2.5-2.fc30.noarch                                @updates-testing
    Upgrade  dnf-yum-4.2.5-2.fc30.noarch                                 @updates-testing
    Upgrade  ebtables-compat-2.0.10-36.fc30.x86_64                       @updates-testing
    Upgrade  ebtables-legacy-2.0.10-36.fc30.x86_64                       @updates-testing
    Upgrade  ebtables-services-2.0.10-36.fc30.x86_64                     @updates-testing
    Upgrade  enchant2-2.2.4-2.fc30.x86_64                                @updates-testing
    Upgrade  expat-2.2.7-1.fc30.i686                                     @updates-testing
    Upgrade  expat-2.2.7-1.fc30.x86_64                                   @updates-testing
    Upgrade  gdb-8.3-5.fc30.x86_64                                       @updates-testing
    Upgrade  gdb-headless-8.3-5.fc30.x86_64                              @updates-testing
    Upgrade  hplip-3.18.12-13.fc30.x86_64                                @updates-testing
    Upgrade  hplip-common-3.18.12-13.fc30.x86_64                         @updates-testing
    Upgrade  hplip-libs-3.18.12-13.fc30.x86_64                           @updates-testing
    Upgrade  initscripts-10.02-1.fc30.x86_64                             @updates-testing
    Upgrade  libinput-1.13.4-1.fc30.x86_64                               @updates-testing
    Upgrade  libnice-0.1.16-5.fc30.x86_64                                @updates-testing
    Upgrade  libsane-hpaio-3.18.12-13.fc30.x86_64                        @updates-testing
    Upgrade  python3-dnf-4.2.5-2.fc30.noarch                             @updates-testing
    Upgrade  qt5-qtwayland-5.12.4-2.fc30.x86_64                          @updates-testing
    Upgrade  qt5-qtwebengine-5.12.4-5.fc30.x86_64                        @updates-testing
    Upgrade  tpm2-tools-3.2.0-1.fc30.x86_64                              @updates-testing
    Upgrade  flatpak-1.4.2-1.fc30.x86_64                                 @updates
    Upgrade  flatpak-libs-1.4.2-1.fc30.x86_64                            @updates
    Upgrade  flatpak-selinux-1.4.2-1.fc30.x86_64                         @updates
    Upgrade  gnome-calculator-3.32.2-1.fc30.x86_64                       @updates
    Upgrade  hwdata-0.325-1.fc30.noarch                                  @updates
    Upgrade  mesa-dri-drivers-19.0.8-1.fc30.i686                         @updates
    Upgrade  mesa-dri-drivers-19.0.8-1.fc30.x86_64                       @updates
    Upgrade  mesa-filesystem-19.0.8-1.fc30.i686                          @updates
    Upgrade  mesa-filesystem-19.0.8-1.fc30.x86_64                        @updates
    Upgrade  mesa-libEGL-19.0.8-1.fc30.x86_64                            @updates
    Upgrade  mesa-libGL-19.0.8-1.fc30.i686                               @updates
    Upgrade  mesa-libGL-19.0.8-1.fc30.x86_64                             @updates
    Upgrade  mesa-libOpenCL-19.0.8-1.fc30.x86_64                         @updates
    Upgrade  mesa-libgbm-19.0.8-1.fc30.x86_64                            @updates
    Upgrade  mesa-libglapi-19.0.8-1.fc30.i686                            @updates
    Upgrade  mesa-libglapi-19.0.8-1.fc30.x86_64                          @updates
    Upgrade  mesa-libxatracker-19.0.8-1.fc30.x86_64                      @updates
    Upgrade  mesa-vulkan-drivers-19.0.8-1.fc30.i686                      @updates
    Upgrade  mesa-vulkan-drivers-19.0.8-1.fc30.x86_64                    @updates
    Upgrade  mutter-3.32.2-3.fc30.x86_64                                 @updates
    Upgrade  vim-common-2:8.1.1602-1.fc30.x86_64                         @updates
    Upgrade  vim-enhanced-2:8.1.1602-1.fc30.x86_64                       @updates
    Upgrade  vim-filesystem-2:8.1.1602-1.fc30.noarch                     @updates
    Upgrade  vim-minimal-2:8.1.1602-1.fc30.x86_64                        @updates
    Upgrade  xorg-x11-server-Xorg-1.20.5-3.fc30.x86_64                   @updates
    Upgrade  xorg-x11-server-Xwayland-1.20.5-3.fc30.x86_64               @updates
    Upgrade  xorg-x11-server-common-1.20.5-3.fc30.x86_64                 @updates
    Upgrade  opera-stable-62.0.3331.18-0.x86_64                          @opera

    Upgrade  palemoon-28.6.0.1-1.x86_64                            @bgstack15-palemoon
    Upgrade  abrt-2.12.1-1.fc30.x86_64                             @updates-testing
    Upgrade  abrt-addon-ccpp-2.12.1-1.fc30.x86_64                  @updates-testing
    Upgrade  abrt-addon-coredump-helper-2.12.1-1.fc30.x86_64       @updates-testing
    Upgrade  abrt-addon-kerneloops-2.12.1-1.fc30.x86_64            @updates-testing
    Upgrade  abrt-addon-pstoreoops-2.12.1-1.fc30.x86_64            @updates-testing
    Upgrade  abrt-addon-vmcore-2.12.1-1.fc30.x86_64                @updates-testing
    Upgrade  abrt-addon-xorg-2.12.1-1.fc30.x86_64                  @updates-testing
    Upgrade  abrt-cli-2.12.1-1.fc30.x86_64                         @updates-testing
    Upgrade  abrt-dbus-2.12.1-1.fc30.x86_64                        @updates-testing
    Upgrade  abrt-desktop-2.12.1-1.fc30.x86_64                     @updates-testing
    Upgrade  abrt-gui-2.12.1-1.fc30.x86_64                         @updates-testing
    Upgrade  abrt-gui-libs-2.12.1-1.fc30.x86_64                    @updates-testing
    Upgrade  abrt-libs-2.12.1-1.fc30.x86_64                        @updates-testing
    Upgrade  abrt-plugin-bodhi-2.12.1-1.fc30.x86_64                @updates-testing
    Upgrade  abrt-retrace-client-2.12.1-1.fc30.x86_64              @updates-testing
    Upgrade  abrt-tui-2.12.1-1.fc30.x86_64                         @updates-testing
    Upgrade  adwaita-qt4-1.0.90-1.fc30.x86_64                      @updates-testing
    Upgrade  adwaita-qt5-1.0.90-1.fc30.x86_64                      @updates-testing
    Upgrade  anaconda-30.25.6-4.fc30.x86_64                        @updates-testing
    Upgrade  anaconda-core-30.25.6-4.fc30.x86_64                   @updates-testing
    Upgrade  anaconda-gui-30.25.6-4.fc30.x86_64                    @updates-testing
    Upgrade  anaconda-install-env-deps-30.25.6-4.fc30.x86_64       @updates-testing
    Upgrade  anaconda-tui-30.25.6-4.fc30.x86_64                    @updates-testing
    Upgrade  anaconda-widgets-30.25.6-4.fc30.x86_64                @updates-testing
    Upgrade  curl-7.64.0-8.fc30.x86_64                             @updates-testing
    Upgrade  dnf-4.2.7-1.fc30.noarch                               @updates-testing
    Upgrade  dnf-data-4.2.7-1.fc30.noarch                          @updates-testing
    Upgrade  dnf-yum-4.2.7-1.fc30.noarch                           @updates-testing
    Upgrade  enchant2-2.2.5-1.fc30.x86_64                          @updates-testing
    Upgrade  fuse-common-3.6.1-2.fc30.x86_64                       @updates-testing
    Upgrade  gdb-8.3-6.fc30.x86_64                                 @updates-testing
    Upgrade  gdb-headless-8.3-6.fc30.x86_64                        @updates-testing
    Upgrade  gnupg2-2.2.16-1.fc30.x86_64                           @updates-testing
    Upgrade  gnupg2-smime-2.2.16-1.fc30.x86_64                     @updates-testing
    Upgrade  kernel-headers-5.1.16-300.fc30.x86_64                 @updates-testing
    Upgrade  libbytesize-2.1-1.fc30.x86_64                         @updates-testing
    Upgrade  libcurl-7.64.0-8.fc30.i686                            @updates-testing
    Upgrade  libcurl-7.64.0-8.fc30.x86_64                          @updates-testing
    Upgrade  libdnf-0.35.1-1.fc30.x86_64                           @updates-testing
    Upgrade  libdrm-2.4.99-1.fc30.i686                             @updates-testing
    Upgrade  libdrm-2.4.99-1.fc30.x86_64                           @updates-testing
    Upgrade  libmodulemd-2.6.0-1.fc30.x86_64                       @updates-testing
    Upgrade  libmodulemd1-1.8.13-1.fc30.x86_64                     @updates-testing
    Upgrade  libreport-2.10.1-1.fc30.x86_64                        @updates-testing
    Upgrade  libreport-anaconda-2.10.1-1.fc30.x86_64               @updates-testing
    Upgrade  libreport-cli-2.10.1-1.fc30.x86_64                    @updates-testing
    Upgrade  libreport-fedora-2.10.1-1.fc30.x86_64                 @updates-testing
    Upgrade  libreport-filesystem-2.10.1-1.fc30.noarch             @updates-testing
    Upgrade  libreport-gtk-2.10.1-1.fc30.x86_64                    @updates-testing
    Upgrade  libreport-plugin-bugzilla-2.10.1-1.fc30.x86_64        @updates-testing
    Upgrade  libreport-plugin-kerneloops-2.10.1-1.fc30.x86_64      @updates-testing
    Upgrade  libreport-plugin-logger-2.10.1-1.fc30.x86_64          @updates-testing
    Upgrade  libreport-plugin-reportuploader-2.10.1-1.fc30.x86_64  @updates-testing
    Upgrade  libreport-plugin-systemd-journal-2.10.1-1.fc30.x86_64 @updates-testing
    Upgrade  libreport-plugin-ureport-2.10.1-1.fc30.x86_64         @updates-testing
    Upgrade  libreport-web-2.10.1-1.fc30.x86_64                    @updates-testing
    Upgrade  libssh-0.9.0-2.fc30.i686                              @updates-testing
    Upgrade  libssh-0.9.0-2.fc30.x86_64                            @updates-testing
    Upgrade  net-snmp-libs-1:5.8-10.fc30.x86_64                    @updates-testing
    Upgrade  nss-3.44.1-1.fc30.i686                                @updates-testing
    Upgrade  nss-3.44.1-1.fc30.x86_64                              @updates-testing
    Upgrade  nss-softokn-3.44.1-1.fc30.i686                        @updates-testing
    Upgrade  nss-softokn-3.44.1-1.fc30.x86_64                      @updates-testing
    Upgrade  nss-softokn-freebl-3.44.1-1.fc30.i686                 @updates-testing
    Upgrade  nss-softokn-freebl-3.44.1-1.fc30.x86_64               @updates-testing
    Upgrade  nss-sysinit-3.44.1-1.fc30.x86_64                      @updates-testing
    Upgrade  nss-util-3.44.1-1.fc30.i686                           @updates-testing
    Upgrade  nss-util-3.44.1-1.fc30.x86_64                         @updates-testing
    Upgrade  openblas-0.3.6-2.fc30.x86_64                          @updates-testing
    Upgrade  openblas-serial-0.3.6-2.fc30.x86_64                   @updates-testing
    Upgrade  pcre2-10.33-6.fc30.i686                               @updates-testing
    Upgrade  pcre2-10.33-6.fc30.x86_64                             @updates-testing
    Upgrade  pcre2-utf16-10.33-6.fc30.x86_64                       @updates-testing
    Upgrade  python3-abrt-2.12.1-1.fc30.x86_64                     @updates-testing
    Upgrade  python3-abrt-addon-2.12.1-1.fc30.x86_64               @updates-testing
    Upgrade  python3-bytesize-2.1-1.fc30.x86_64                    @updates-testing
    Upgrade  python3-dnf-4.2.7-1.fc30.noarch                       @updates-testing
    Upgrade  python3-hawkey-0.35.1-1.fc30.x86_64                   @updates-testing
    Upgrade  python3-libdnf-0.35.1-1.fc30.x86_64                   @updates-testing
    Upgrade  python3-libreport-2.10.1-1.fc30.x86_64                @updates-testing
    Upgrade  qt-settings-30.2-1.fc30.noarch                        @updates-testing
    Upgrade  webkit2gtk3-2.24.3-1.fc30.x86_64                      @updates-testing
    Upgrade  webkit2gtk3-jsc-2.24.3-1.fc30.x86_64                  @updates-testing
    Upgrade  webkit2gtk3-plugin-process-gtk2-2.24.3-1.fc30.x86_64  @updates-testing
    Upgrade  xen-libs-4.11.2-1.fc30.x86_64                         @updates-testing
    Upgrade  xen-licenses-4.11.2-1.fc30.x86_64                     @updates-testing

Hope that helps.  Thanks for your work on autokey - it's one of my favorite, most useful tools.

**Comment by qlixed** [comment]
Quick recommendation: I use fedora 30 too, but use the pip installation for the autokey package: No issues so far!.

**Comment by dlewis7444** [comment]
Tried that.  Uninstalled with dnf.  Installed with pip.  Same issues.  (Reverted back to dnf then).

Something in the updates fixed it for me.  Although I still don't have an icon in the message tray.

**Comment by qlixed** [comment]
You use pip --user? or do a systemwide install with sudo pip?
I use pip --user to keep self-contained the dependecies, isolated from the OS updates. Maybe that is the difference.

I'm currently have this installed on my system (autokey and deps):

$ pip3 list | grep -Ei "autokey|inotify|xlib|PyGObject"
autokey                       0.95.4     
PyGObject                     3.32.1     
pyinotify                     0.9.6      
python-xlib                   0.25       

$ pip3 list --user  | grep -Ei "autokey|inotify|xlib|PyGObject"
autokey                       0.95.4  
python-xlib                   0.25    

$ dnf list --installed | grep -Ei "autokey|inotify|xlib|PyGObject"
pygobject2.x86_64                                      2.28.7-5.fc30                               @fedora                   
pygobject3-devel.x86_64                                3.32.1-1.fc30                               @updates                  
python2-inotify.noarch                                 0.9.6-15.fc30                               @fedora                   
python2-xlib.noarch                                    0.23-4.fc30                                 @fedora                   
python3-inotify.noarch                                 0.9.6-15.fc30                               @fedora                   
rubygem-rb-inotify.noarch                              0.10.0-1.fc30                               @fedora

Maybe that could helps.

**Comment by dlewis7444** [comment]
Pretty sure I did a --user.  I'll try it again - but not today: got a meeting coming and then I'm outta here.

**Comment by dlewis7444** [comment]
Yeah, no diff.

I wondered if it was one of my gnome-extensions conflicting.  I have things like the Applications and Places menu, Window List, NetSpeed...  Anyway, tried turning them all off and rebooting.  Then I tried setenforce 0.  Then I tried setting the SUID bit on autokey-gtk.  No joy.

Icon does not show with autokey-qt either.

@luziferius My main problem, not grabbing the keyboard, has been solved.  If you want to close this ticket, that's cool.  The missing icon is minor.  I'm happy to provide add'l info if you WANT to troubleshoot it, but I'd rather live with it.

Edit: oh, didn't realize I could close it.  Hehe

**Comment by nathancurry** [comment]
Experiencing this issue with Fedora 31.

The answer is, as with most things in life, Wayland.

**Comment by josephj11** [comment]
@nathancurry AFAIK, Wayland is missing things AutoKey needs to work. Currently, AutoKey only works with X11 and there are no plans to adapt it to Wayland (although I think the developers would be open to someone working on it.)

What version of AutoKey are you using? 0.95.9 is the current version.
Have you tried using the autokey-qt front end? One of the posters above had luck with that.
If the problem persists for you (doesn't get fixed by updating something else on your system), then we'll need [more information](https://github.com/autokey/autokey-python2/wiki/Problem-Reporting-Guide) from you including a trace.

**Comment by nathancurry** [comment]
I just stopped using Wayland. I'd forgotten that it's the default on
Fedora, despite still not working with a ton of stuff. I commented in case
someone else ran into the same issue they would have an answer.

Thanks!
