### ISSUE TITLE
autokey freezes on shift+insert paste if the clipboard contains image data at time of phrase expansion

### ISSUE THREAD

**Issue by gruns** [autokey/autokey#573]
## Classification:

Crash/Hang

## Reproducibility:

Always

## Version

AutoKey version: autokey==0.95.4

Used GUI (Gtk, Qt, or both): gtk

Linux Distribution: Linux Mint 18.3 Sylvia

## Summary

if the clipboard contains image content, eg a screenshot taken with flameshot (https://github.com/flameshot-org/flameshot) copied to the clipboard, and a phrase paste from the clipboard occurs with shift+insert, autokey freezes, crashes, and locks the keyboard

autokey must then be killed, like over ssh (because keyboard input is broken)

## Steps to Reproduce (if applicable)

- take a screenshot with flameshot and copy it to the clipboard
- trigger a shift+insert paste, eg with a Phrase

## Expected Results

- the abbreviation is deleted
- the phrase text is pasted

## Actual Results

- the abbreviation is deleted
- the phrase is not pasted
- autokey freezes, stopping all keyboard input, and must be killed via ssh

**Comment by josephj11** [comment]
Several things here.

* Currently, AutoKey cannot deal with non-text objects in the clipboard. Some work has been done on this, but I'm not sure if it made it into our beta release (0.96) which we are currently testing.
* Regardless of the above, this is a bug and AutoKey should be able to detect this and fail gracefully.
* Mint is Debian-based, so if you install/upgrade AutoKey from your repositories, you should have 0.95.10 which is much improved over 0.95.4 - but will not solve the current issue.

**Comment by gruns** [comment]
> Currently, AutoKey cannot deal with non-text objects in the clipboard.

ya. the odd thing about this bug is that, outwardly, whatever the contents of the clipboard are at the time of phrase activation should be irrelevant, as those content should be overwritten by autokey (with the replacement phrase) and then pasted immediately thereafter

perhaps autokey tries to read the non-text clipboard content first and that's where it bombs

> Mint is Debian-based, so if you install/upgrade AutoKey from your repositories, you should have 0.95.10 which is much improved over 0.95.4 - but will not solve the current issue.

ill give 0.95.10 a shot 💪

thank you @josephj11 🙏

**Comment by ineuw** [comment]
Autokey does not clear the clipboard automatically. You have to do it from the phrase or script. If the previous contents were text, it appends it to the phrase you are pasting.

**Comment by gruns** [comment]
interesting. that could immediately explain why autokey bombs if: 1) autokey does not clear the non-text clipboard content and 2) attempts to append the non-text clipboard content to the replacement phrase text

that said, i dont understand why autokey would append the previous clipboard contents to the phrase being pasted. why would autokey not overwrite the clipboard contents on `Paste using (Shift+Insert)`? example:

- the text `i love penguins` resides in the clipboard from some activity 15 minutes ago
- i type some text and then type `123`, an expanding phrase for `12345`
- autokey should, ostensibly, overwrite `i love penguins` in the clipboard with `12345`, delete `123`, and then paste `12345`. it should not paste `12345i love penguins`

this is the behavior i observe when `Paste using Keyboard` is used, too: `12345` is pasted, not `12345i love penguins`

**Comment by gruns** [comment]
> Mint is Debian-based, so if you install/upgrade AutoKey from your repositories, you should have 0.95.10 which is much improved over 0.95.4 - but will not solve the current issue.

also just fyi, 0.90.4-1 is the latest available in the mint repos for my, admittedly old, mint 18.3

```
$ apt list | grep -i autokey
autokey-common/xenial,xenial,now 0.90.4-1 all [residual-config]
autokey-gtk/xenial,xenial 0.90.4-1 all
autokey-qt/xenial,xenial 0.90.4-1 all
```

**Comment by ineuw** [comment]
Why are you all going backwards? Why go to the Software Store? There are clear instructions to upgrade to the latest stable is 95.10. There is no ppa. This is a far superior version to the one you are discussing.

As for clearing the clipboard, there has been numerous discussions on Autokey forums.

**Comment by josephj11** [comment]
@gruns Yes, we had no Debian package maintainer for quite a few years so their version (and for every distro that used their version) was stuck there. That was fixed a year or two ago.

For now, use [these instructions](https://github.com/autokey/autokey/wiki/Installing#debian-and-derivatives) to upgrade.

**Comment by gruns** [comment]
> AutoKey version: autokey==0.95.4
>
> Why are you all going backwards?

i installed v0.95.4, the latest in pypi

  * https://pypi.org/project/autokey/#history

> For now, use these instructions to upgrade.

sick. thank you! 🙏

**Comment by ineuw** [comment]
If your paste still includes previous information, that means that the old info was stored in the X-PRIMARY clipboard buffer and served up to the X-CLIPBOARD until the X-PRIMARY is cleared. This is an X feature assigned to the middle mouse button. I experimented with this and found a solution by disabling the copy/paste/transfer of the middle button/scroller click. There are many solutions and I am not qualified to comment on them. I recommend to ourselves (you and me) to install a third party GUI X-clipboards viewers. There are a few of them around as well.

To clear the clipboard, I am experimenting and successful so far at clearing both clipboards with xsel. This 0.5 second delay is consistently reliable delay to clear the X-CLIPBOARD containing 3500 characters of text. Mouse access is already disabled but I included it in the following just in case: 

-c = clear, -p = primary, -b = clipboard

`os.system("xsel -c -p -b")`
`time.sleep(0.5)`

I hope this helps.

**Comment by gruns** [comment]
for future intrepid explorers of this issue: v0.95.4 fixed the hard locks of autokey. yay!

but the copy/paste behavior still doesn't work 100% of the time. sometimes, with `Paste using: Shift+Insert`, the prior clipboard contents aren't replaced with the phrase and thus the prior clipboard's contents are mistakenly pasted instead

that said, this is a *huge* improvement over autokey hard locking and requiring `ssh` to kill remotely. huge kudos to the team 🙌

**Comment by josephj11** [comment]
If you are still using 0.95.4, you should really upgrade to 0.95.10 which has a number of fixes in it.
