### ISSUE TITLE
Hotstrings not working

### ISSUE THREAD

**Issue by PatrickRoesler** [autokey/autokey#717]
### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Bug

### Which Linux distribution did you use?

Fedora 34

uname -r puts out:
5.17.12-100.fc34.x86_64

### Which AutoKey GUI did you use?

GTK

### Which AutoKey version did you use?

0.95.10

### How did you install AutoKey?

sudo dnf install autokey-gtk.noarch

### Can you briefly describe the issue?

Hello, I tried to configure a hotstring. What I wanted is, when typing "btw" it should be automatically replaced with "by the way". It´s just not working. I´m not sure maybe it is my own fault, because I need to configure something more.

I tried different things selecting these checkboxes (see attachment).

![Bildschirmfoto von 2022-07-27 09-14-04](https://user-images.githubusercontent.com/61048262/181185189-ad0ae015-1174-4f4c-9ca6-451ab908d845.png)

### Can the issue be reproduced?

Always

### What are the steps to reproduce the issue?

1. Create abbreviation as it is in attachment.
2. Save it
3. Open any tool where you can enter text (Terminal, Text editor, PHPStorm, Mail Client, or whatever)
4. Type in abbreviation
5. Either press return or spacebar

-> Expected the abbreviation to be replaced right now

### What should have happened?

Already said it in "What are the steps to reproduce the issue?"

### What actually happened?

Abbrevation is still typed in and not replaced, in case of using spacebar it is "btw ".

### Can you provide the output of the AutoKey command?

```bash
There is no output.
```

**Comment by Elliria** [comment]
This is a known issue (see issue #667) that might have been fixed in the latest version, but I'm not using that one. I'm using the same version you are.

The way to add an abbreviation is to click the "**Set**" button, then click the "**Add+**" button, then type in the abbreviation, then press the "**Enter**" key, and then click the "**OK**" button.

**Comment by josephj11** [comment]
@Elliria  It's not clear to me whether this is that issue or not

@PatrickRoesler First, make sure you have actually saved your changes. The Save button on the AutoKey menu will be disabled (grayed out) if no changes are unsaved.

Once you have added you trigger abbreviation and saved your changes, select a different phrase or script for a moment and then come back to the one in question. Your new abbreviation should still be there if it was successfully assigned and saved. Is that the case? If so, then it's not the same as that other issue.

in the main AutoKey Menu, select Settings. You should see a drop down menu and the Enable Monitoring checkbox should be filled in (it is by default). If that's off, AutoKey won't do anything.

If none of the above help, then we'll have to run a trace, but let's get that much eliminated first.

**Comment by Elliria** [comment]
Yep. I totally misread that and thought it was a failure to set the hotkey.

From looking at the screenshot, the press of the **Enter** key or **space bar** shouldn't be necessary. The abbreviation should fire the instant the hotkey is typed.

@PatrickRoesler, are you using Wayland? The Fedora project says that starting with Plasma 5.20 in Fedora 34, they're making Wayland the default session. It looks like they still provide X11, so if you're using Wayland, you might want to try switching to X11 and seeing if that takes care of it.

**Comment by josephj11** [comment]
@Elliria Team tag! Good catch.  AutoKey is not compatible with Wayland, so if that is running nothing will work. Although most distros are switching to Wayland as the default, they still have the option to select X11 instead.

**Comment by PatrickRoesler** [comment]
Hello everybody,

`ps aux | grep -i wayland` puts out:

```
proesler    2275  0.0  0.0 374348  5940 tty2     Ssl+ 08:36   0:00 /usr/libexec/gdm-wayland-session /usr/bin/gnome-session
proesler    3114  3.3  0.8 1407976 114520 ?      Sl   08:36   0:46 /usr/bin/Xwayland :0 -rootless -noreset -accessx -core -auth /run/user/1000/.mutter-Xwaylandauth.N7PHQ1 -listenfd 4 -listenfd 5 -displayfd 6 -initfd 7
root        9310  0.0  0.0 221552  2520 pts/1    S+   08:59   0:00 grep --color=auto -i wayland
```

So using wayland seems to be the cause.

But I think there is another point: When all distros go ahead using wayland and kalarm is not compatible then I think it´s up to the kalarm maintainers anyway to do something ;-) The only alternative is to give kalarm up.

When all distros decide to use wayland by default there must be good reasons for it I guess. So it would not be a good decision to "stop the evolution" just to make "an old tool" keep working that is not willing to go the way.

I know this is just a general attitude. Maybe in this case there are any good reasons I just don´t know for making another decision.

Greetings

**Comment by Elliria** [comment]
Team tag right back at you, @josephj11.

Thank you for checking and verifying that you're using Wayland, @PatrickRoesler. I understand the frustration with the current transition phase that we're in with these two very different desktops, but there may be some good news. According to this partial quote from the [Wayland FAQ](https://wayland.freedesktop.org/faq.html#heading_toc_j_4):

> "...there are some clients which rely on X11, and always will be. To that end, XWayland provides a plugin for Wayland compositors, running a real X server. This gives legacy clients a real and compliant X11 platform to run on, displayed side by side with native Wayland clients in your Wayland session."

I find the "**and always will be**" part very reassuring and would love to hear from someone who has some experience in using that X plugin under Wayland.

Development of AutoKey is done on a voluntary basis by a very small number of people who can't devote all of their time to it. We're very grateful for anything they can do while at the same time hoping for and [welcoming contributions from anyone new](https://github.com/autokey/autokey/wiki/Contributing-code) (perhaps you) who would like to give AutoKey development a try.

Converting a program from one platform to another is probably the most difficult task any developer can face because it involves rethinking the whole project and the small details can become a programming nightmare. Nicolas Stouff did a thorough and interesting examination of Wayland and why it will be difficult to adopt in [a video on his "The Linux Experiment" channel](https://www.youtube.com/watch?v=g1BoZnekkyM). After watching that video, I suspect that even a full-time dedicated team would be sweating it to make this happen for AutoKey, but there are several of us who will be cheering them on and doing what we can at our end to help.

**Comment by josephj11** [comment]
For anyone interested, the relevant AutoKey issues are #87, #503, #600, and, maybe, #710.

**Comment by Elliria** [comment]
Thanks, @josephj11. Sadly, that list will surely be getting bigger soon.
